/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controllers.AnalyseController;
import Controllers.ClientController;
import Controllers.OrderController;
import Entities.Analysis;
import Entities.Client;
import Entities.Order;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import utilities.AnalysisTableModel;
import utilities.ClientsTableModel;
import utilities.GuiListModels;
import utilities.OrdersTabelModel;
import utilities.ResultsTableModel;

/**
 *
 * @author User
 */

public class ResultsPane extends javax.swing.JPanel {

    /**
     * Creates new form ResultsPane
     */
    private final ClientsTableModel clientModel = new ClientsTableModel();
    private final OrdersTabelModel orderModel = new OrdersTabelModel();
    private final ResultsTableModel analysisModel = new ResultsTableModel();
    private final GuiListModels<Order> searchModel = new GuiListModels();
    private Order o;
    
    public ResultsPane() {
        initComponents();
        clientsTable.getColumnModel().getColumn(0).setMinWidth(256);
        clientsTable.getColumnModel().getColumn(0).setMaxWidth(256);
        clientsTable.getColumnModel().getColumn(1).setMinWidth(128);
        clientsTable.getColumnModel().getColumn(1).setMaxWidth(128);
//        ordersTable.getColumnModel().getColumn(0).setMinWidth(256);
//        ordersTable.getColumnModel().getColumn(0).setMaxWidth(256);
//        ordersTable.getColumnModel().getColumn(1).setMinWidth(128);
//        ordersTable.getColumnModel().getColumn(1).setMaxWidth(128);
        analysisTable.getColumnModel().getColumn(0).setMinWidth(256);
        analysisTable.getColumnModel().getColumn(0).setMaxWidth(256);
        analysisTable.getColumnModel().getColumn(1).setMinWidth(128);
        analysisTable.getColumnModel().getColumn(1).setMaxWidth(128);
        clientsTable.setModel(clientModel);
//        ordersTable.setModel(orderModel);
        analysisTable.setModel(analysisModel);
        listOrder.setModel(searchModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        analysisTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        listOrder = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        selectBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        firstNameField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        clientsTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        clientsTable.setForeground(new java.awt.Color(22, 113, 185));
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        clientsTable.setRowHeight(32);
        jScrollPane1.setViewportView(clientsTable);

        jButton1.setForeground(new java.awt.Color(22, 113, 185));
        jButton1.setText("select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 113, 185));
        jLabel3.setText("First Name");

        jButton3.setForeground(new java.awt.Color(22, 113, 185));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        analysisTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        analysisTable.setForeground(new java.awt.Color(22, 113, 185));
        analysisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        analysisTable.setRowHeight(32);
        jScrollPane3.setViewportView(analysisTable);

        listOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        listOrder.setForeground(new java.awt.Color(0, 102, 102));
        listOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listOrderMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(listOrder);

        jSeparator1.setForeground(new java.awt.Color(22, 113, 185));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        selectBtn.setForeground(new java.awt.Color(22, 113, 185));
        selectBtn.setText("select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameField.getText();
        clientModel.removeAll();
        new SearchClientPerformed(firstName).execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       Analysis a = analysisModel.get(analysisTable.getSelectedRow());
       new AddResultWorker(o,a).execute();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        Client client=clientModel.get(clientsTable.getSelectedRow());
        new SearchOrdersWorker(client).execute();
    }//GEN-LAST:event_selectBtnActionPerformed

    private void listOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOrderMousePressed
        // TODO add your handling code here:
        o = (Order) listOrder.getSelectedValue();
        o.listAnalysis = new ArrayList();
        new GetAnalysisWorker(o).execute();
    }//GEN-LAST:event_listOrderMousePressed

private class SearchClientPerformed extends SwingWorker<List<Client>, Void> {

        private final String fName;

        public SearchClientPerformed(String firstName) {
            this.fName = firstName;
        }

        @Override
        protected List<Client> doInBackground() throws Exception {
            return ClientController.instance.findByLike(fName);
        }

        @Override
        public void done() {
            //Table tab = new Table();
            try {
                clientModel.set(get());
                clientsTable.setModel(clientModel);
                repaint();
            } catch (InterruptedException ex) {
                Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(OrderFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
private class SearchOrdersWorker extends SwingWorker<List<Order>, Void> {
    
    Client client;
    public SearchOrdersWorker(Client client){
        this.client = client;
    }

        @Override
        protected List<Order> doInBackground() throws Exception {
            return OrderController.instance.findByClient(client);
            
            
        }
        public void done() {
            searchModel.removeAll();
            try {
                searchModel.set(get());
            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(ResultsPane.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
private class GetAnalysisWorker extends SwingWorker<Order, Void> {
    Order o;
    public GetAnalysisWorker(Order o){
        this.o = o;
    }

        @Override
        protected Order doInBackground() throws Exception {
         return AnalyseController.instance.findByOrder(o);   
        }
        public void done() {
            analysisModel.removeAll();
            try {
                o = get();
                analysisModel.set(o.listAnalysis);
            } catch (ExecutionException ex) {
                Logger.getLogger(ResultsPane.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
            Logger.getLogger(ResultsPane.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    
}
private class AddResultWorker extends SwingWorker<String, Void> {
    
    Order o;
    Analysis a;
    public AddResultWorker(Order o , Analysis a){
        this.o = o;
        this.a = a;
    }

        @Override
        protected String doInBackground() throws Exception {
            try {
               // System.out.println(client);
                AnalyseController.instance.addResult(o);
            } catch (SQLException ex) {
                System.out.println("error of controller output ");
                return ex.getMessage();
            }
            return null;
        }

        @Override
        public void done() {
            try {
                if (get() == null) {
                    JOptionPane.showMessageDialog(ResultsPane.this,
                            " has been added successfully",
                            "Successful adding",
                            JOptionPane.INFORMATION_MESSAGE);
                   
                } else {
                    JOptionPane.showMessageDialog(ResultsPane.this,
                            " has errors",
                            "entry error",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(editClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(editClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable analysisTable;
    private javax.swing.JTable clientsTable;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listOrder;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
